# Generated by Django 4.2 on 2023-12-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('lowercase_name', models.CharField(editable=False, max_length=64)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(choices=[('current', 'Погода в данный момент'), ('night', 'Ночь'), ('morning', 'Утро'), ('day', 'День'), ('evening', 'Вечер')], max_length=10)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.city')),
            ],
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['lowercase_name', 'longitude', 'latitude'], name='unique_city_coords'),
        ),
    ]
