# Generated by Django 4.2 on 2023-12-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='unique_identifier',
            field=models.CharField(default='default_value', editable=False, max_length=128, unique=True),
        ),
    ]
