# Generated by Django 4.2 on 2023-12-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_city_unique_identifier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='city',
            name='unique_city_coords',
        ),
    ]
