# Generated by Django 4.2 on 2023-12-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_remove_city_unique_city_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lowercase_name',
        ),
        migrations.AlterField(
            model_name='weather',
            name='time_of_day',
            field=models.CharField(max_length=10),
        ),
    ]
